"""Stable PCAM result and fault codes for the reference slice."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class ResultCode(str, Enum):
    OK = "OK"
    INVALID_INPUT = "INVALID_INPUT"
    IO_ERROR = "IO_ERROR"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    DEFINITION_REJECTED = "DEFINITION_REJECTED"
    RUNTIME_FAULT = "RUNTIME_FAULT"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    SNAPSHOT_DEFINITION_MISMATCH = "SNAPSHOT_DEFINITION_MISMATCH"
    CANONICALIZATION_FAILURE = "CANONICALIZATION_FAILURE"


class PCAMFault(str, Enum):
    INVALID_DOCUMENT = "INVALID_DOCUMENT"
    UNSUPPORTED_DEFINITION_KIND = "UNSUPPORTED_DEFINITION_KIND"
    INVALID_PROFILE_RANGE = "INVALID_PROFILE_RANGE"
    PREDICATE_CYCLE = "PREDICATE_CYCLE"
    MISSING_REFERENCE = "MISSING_REFERENCE"
    INVALID_NODE_DURATION = "INVALID_NODE_DURATION"
    MISSING_COMPLETION_PATH = "MISSING_COMPLETION_PATH"
    INTEGER_OVERFLOW = "INTEGER_OVERFLOW"
    DIVISION_BY_ZERO = "DIVISION_BY_ZERO"
    QUANTUM_LIMIT_EXCEEDED = "QUANTUM_LIMIT_EXCEEDED"
    TRANSITION_LIMIT_EXCEEDED = "TRANSITION_LIMIT_EXCEEDED"
    UNKNOWN_EFFECT = "UNKNOWN_EFFECT"
    SNAPSHOT_DEFINITION_MISMATCH = "SNAPSHOT_DEFINITION_MISMATCH"
    CANONICALIZATION_FAILURE = "CANONICALIZATION_FAILURE"
    STATE_INVARIANT_FAILURE = "STATE_INVARIANT_FAILURE"
    INVALID_CANONICAL_IDENTIFIER = "INVALID_CANONICAL_IDENTIFIER"
    DUPLICATE_TRANSITION_PRIORITY = "DUPLICATE_TRANSITION_PRIORITY"


@dataclass(frozen=True)
class PCAMError(Exception):
    code: ResultCode
    fault: PCAMFault
    message: str

    def __str__(self) -> str:
        return f"{self.code.value}:{self.fault.value}:{self.message}"
